# Generated by Django 5.2.4 on 2026-02-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_default_language_swahili'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('ticket_type', models.CharField(choices=[('complaint', 'Malalamiko'), ('question', 'Swali')], max_length=16)),
                ('ticket_id', models.CharField(db_index=True, max_length=32)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('received', 'Imepokelewa'), ('in_progress', 'Inakaguliwa'), ('answered', 'Imegibiwa')], default='received', max_length=20)),
                ('department', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
