# Generated by Django 5.2.4 on 2026-02-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_add_ticket_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='feedback',
            field=models.TextField(blank=True, help_text='Admin response sent to customer via WhatsApp'),
        ),
    ]
